### PR TITLE
Fix agent to mark conditions with appropriate status on uninstall

### LINKED ISSUE #585: On using installer controller, after you delete the cluster and create a new cluster then agent is not executing installation script
**What steps did you take and what happened:**
- Started byoh agent using `--use-installer-controller` flag. 
- Create a cluster using K8sInstallerConfigTemplate as installer reference for ByoMachine
- Once host is "provisioned", delete the cluster
- Create a new cluster and you will see that byoh agent won't execute the installation script

**What did you expect to happen:**
byoh-agent should execute the installation script everytime it is attached to the new byomachine.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-bringyourownhost version: 
- Kubernetes version: (use `kubectl version --short`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by shubham14bajpai**
Signed-off-by: Shubham <shbajpai@vmware.com>

**What this PR does / why we need it**:

This PR marks the K8sComponentsInstallationSucceeded condition as false whenever a host a removed from the cluster and the uninstall is executed successfully. It also fixes an existing test by asserting the correct condition for it's status.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #585 

**Additional information**

**Special notes for your reviewer**

### CODE REVIEW

**Review by khannakshat7 — APPROVED** [review]
LGTM 👍🏻

File: agent/reconciler/host_reconciler.go [hunk 1]
```diff
@@ -285,6 +285,7 @@ func (r *HostReconciler) hostCleanUp(ctx context.Context, byoHost *infrastructur
 				r.Recorder.Event(byoHost, corev1.EventTypeWarning, "UninstallScriptExecutionFailed", "uninstall script execution failed")
 				return err
 			}
+			conditions.MarkFalse(byoHost, infrastructurev1beta1.K8sComponentsInstallationSucceeded, infrastructurev1beta1.K8sNodeAbsentReason, clusterv1.ConditionSeverityInfo, "")
 		} else {
 			err = r.uninstallk8sComponents(ctx, byoHost)
```
Comment (anusha94) [inline agent/reconciler/host_reconciler.go:290]: should we mark False after this call too? Because currently we are having 2 ways to uninstall

Comment (shubham14bajpai) [reply agent/reconciler/host_reconciler.go:290]: We are going to deprecate this code in #580 very soon so I thought less code to delete 🙂

Comment (shubham14bajpai) [reply agent/reconciler/host_reconciler.go:290]: I we add that we need another test to to maintain code coverage and then delete it again.

**Review by anusha94 — APPROVED** [review]
lgtm

File: agent/reconciler/host_reconciler.go [hunk 2]
```diff
@@ -285,6 +285,7 @@ func (r *HostReconciler) hostCleanUp(ctx context.Context, byoHost *infrastructur
 				r.Recorder.Event(byoHost, corev1.EventTypeWarning, "UninstallScriptExecutionFailed", "uninstall script execution failed")
 				return err
 			}
+			conditions.MarkFalse(byoHost, infrastructurev1beta1.K8sComponentsInstallationSucceeded, infrastructurev1beta1.K8sNodeAbsentReason, clusterv1.ConditionSeverityInfo, "")
```
Comment (shamsher31) [inline agent/reconciler/host_reconciler.go:288]: Do you want to add a log?
```
logger.Info("host a removed from the cluster and the uninstall is executed successfully")
```

**Review by shamsher31 — APPROVED** [review]
Just a minor comment, otherwise LGTM. 👍

File: agent/reconciler/host_reconciler.go (hunk 2 above)
Comment (shubham14bajpai) [reply agent/reconciler/host_reconciler.go:288]: Added 👍

**Review by shamsher31 — APPROVED** [review]
LGTM

**Review by anusha94 — APPROVED** [review]
