### PR TITLE
fixed: Byoh hostinfo.architecture is not matching with the supported bundle name

### LINKED ISSUE #547: Byoh hostinfo.architecture is not matching with the supported bundle name
Byoh `hostinfo.architecture`  is not matching with the supported bundle name.   

byoh agent is setting architecture using `runtime.GOARCH` which provide `amd64` but the bundle name support `x86-64` means, we need to convert `amd64` to `x86-64` in InstallerConfig controller when generating the installation script.

Part of issue: #467

### PR DESCRIPTION
**Pull request by mayur-tolexo**
**What this PR does / why we need it**:
Byoh hostinfo.architecture is not matching with the supported bundle name.
**Solution:**
in installer, replaced the new architecture name with the old one to
match with the bundle name.  

**Extra changes**
- fixed download package script command as output directory need to be created before pulling the bundle.
- Executed firewall enable/disable command only if ufw command exists.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #547

### CODE REVIEW

File: common/installer/installer.go [hunk 1]
```diff
@@ -17,10 +17,20 @@ type K8sInstaller interface {
...
 // NewInstaller will return a new installer
 func NewInstaller(ctx context.Context, osDist, arch, k8sVersion string, downloader BundleDownloader) (K8sInstaller, error) {
+	bundleArchName := arch
+	// replacing the arch name to old name to match with the bundle name
+	if _, exists := archOldNameMap[arch]; exists {
+		bundleArchName = archOldNameMap[arch]
+	}
 	// normalizing os image name and adding arch
-	osArch := strings.ReplaceAll(osDist, " ", "_") + "_" + arch
+	osArch := strings.ReplaceAll(osDist, " ", "_") + "_" + bundleArchName
```
Comment (shubham14bajpai) [inline common/installer/installer.go:33]: This still won't fix the problem as the regex are different for os_detector and host_registration. We need to remove the "LTS" from osDist here. Small comparison test 🙂 : https://go.dev/play/p/QQ4IjESzFDo

Comment (mayur-tolexo) [reply common/installer/installer.go:33]: I have added "LTS" in test cases and it's working fine.  We check for the os distribution using regex: `Ubuntu_20.04.*_x86-64`. So, this won't be a problem.

Comment (shubham14bajpai) [reply common/installer/installer.go:33]: Ohh then it is perfect 👍

**Review by shubham14bajpai — APPROVED** [review]
LGTM

**Review by shubham14bajpai — APPROVED** [review]

File: common/installer/internal/algo/ubuntu20_4k8s.go [hunk 2]
```diff
@@ -123,7 +124,9 @@ BUNDLE_PATH=$BUNDLE_DOWNLOAD_PATH/$BUNDLE_ADDR
 swapon -a && sed -ri '/\sswap\s/s/^#?//' /etc/fstab
 
 ## enable firewall
-ufw enable
+if command -v ufw >>/dev/null; then
```
Comment (dharmjit) [inline common/installer/internal/algo/ubuntu20_4k8s.go:127]: Is this is to check if the `ufw` executable exists?

Comment (mayur-tolexo) [reply common/installer/internal/algo/ubuntu20_4k8s.go:127]: Yes, so that it works on docker host as well (as docker host don’t have ufw command)

**Review by dharmjit — APPROVED** [review]
