### PR TITLE
Fix Host Agent integration tests

### LINKED ISSUE #636: Host Agent Integration tests failing in CI
Host Agent tests are failing in CI for the Context `When the host agent is executed with --bootstrap-kubeconfig` with the below error

```
Unexpected error:
      <*fs.PathError | 0xc0009016b0>: {
          Op: "lstat",
          Path: "/tmp/mgmt.conf",
          Err: <syscall.Errno>0x2,
      }
      lstat /tmp/mgmt.conf: no such file or directory occurred
```

### PR DESCRIPTION
**Pull request by dharmjit**
**What this PR does / why we need it**:
Integration tests for Host Agent are failing as the `EnvTest` created kubeconfig is not copied to `/tmp/mgmt.conf`. This PR fixes that. 
Also to discover such issues in the future, we are also removing `/tmp/mgmt.conf` after each test execution

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #636

### CODE REVIEW

File: agent/host_agent_suite_test.go [hunk 1]
```diff
@@ -177,4 +177,11 @@ func cleanup(ctx context.Context, byoHostContainer *container.ContainerCreateCre
 			e2e.Showf("error removing log file %s: %v", agentLogFile, err)
 		}
 	}
+	_, err = os.Stat(e2e.TempKubeconfigPath)
```
Comment (shivi28) [inline agent/host_agent_suite_test.go:180]: nit:
```
if _, err = os.Stat(e2e.TempKubeconfigPath); err == nil{
     if err = os.Remove(e2e.TempKubeconfigPath); err !=nil{
            e2e.Showf("error removing kubeconfig file %s: %v", e2e.TempKubeconfigPath, err)
     }
}
```

File: test/e2e/docker_helper.go [hunk 2]
```diff
@@ -27,7 +27,7 @@ import (
 
 const (
 	kindImage           = "byoh/node:e2e"
-	tempKubeconfigPath  = "/tmp/mgmt.conf"
+	TempKubeconfigPath  = "/tmp/mgmt.conf"
```
Comment (shivi28) [inline test/e2e/docker_helper.go:30]: Why are we changing the case ? 🤔

**Review by shivi28 — COMMENTED** [review]
One nit, else lgtm

File: test/e2e/docker_helper.go (hunk 2 above)
Comment (sachinkumarsingh092) [reply test/e2e/docker_helper.go:30]: I guess this is to make it a global variable to be used in `agent/host_agent_suite_test.go`.

**Review by sachinkumarsingh092 — APPROVED** [review]

File: test/e2e/docker_helper.go (hunk 2 above)
Comment (dharmjit) [reply test/e2e/docker_helper.go:30]: This issue in the previous PR was not caught as we were persisting the kubeconfig across tests. Now to remove this after each test we have to make this constant exportable.

File: agent/host_agent_suite_test.go (hunk 1 above)
Comment (dharmjit) [reply agent/host_agent_suite_test.go:180]: I do not have any strong opinions here, but for the first check, it is `err == nil` and that might be confusing with this one-liner err handling.

**Review by anusha94 — APPROVED** [review]

File: agent/host_agent_suite_test.go (hunk 1 above)
Comment (shivi28) [reply agent/host_agent_suite_test.go:180]: Makes sense

**Review by shivi28 — COMMENTED** [review]
LGTM
