### PR TITLE
Fix: Read kubeconfig first even with --bootstrap-kubeconfig flag

### LINKED ISSUE #598: Ignore `--bootstrap-kubeconfig` flag when config file already present
**What steps did you take and what happened:**

When we restart byo host agent, and if we passed `--bootstrap-kubeconfig` flag during the restart, then our controller fails with error message:
Screenshot 2022-06-15 at 5 14 20 PM

This happens because when we pass `--bootstrap-kubeconfig` flag again, then it generates the new CSR which is validated against old private key, which throws compatibility issue

**What did you expect to happen:**
To avoid this issue, we should ignore the `--bootstrap-kubeconfig` flag if config is already present in its path.

**Environment:**

- Cluster-api-provider-bringyourownhost version: 
- Kubernetes version: (use `kubectl version --short`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by dharmjit**
**What this PR does / why we need it**:
In the exisitng implementation, If the user passes the `--bootstrap-kubeconfig` in repeated invocations of the agent in the same host, the code flow is to create CSR again, but the k8s API `k8s.io/client-go/util/certificate/csr.RequestCertificate` tries to use the existing CSR and it will fail due to Certificate Key mismatch.  With this PR, `kubeconfig` if existing as `~/.byoh/config` will be used even with the `--bootstrap-kubeconfig` flag passed.

**Which issue(s) this PR fixes** :
Fixes #598

### CODE REVIEW

**Comment by shivi28** [comment]
LGTM 👍

File: agent/main.go [hunk 1]
```diff
@@ -149,15 +150,16 @@ func main() {
 		logger.Error(err, "could not determine hostname")
 		return
 	}
-
+	_, err = os.Stat(registration.GetBYOHConfigPath())
```
Comment (shamsher31) [inline agent/main.go:153]: Should we also check for err?

File: agent/host_agent_test.go [hunk 2]
```diff
@@ -561,7 +563,57 @@ var _ = Describe("Agent", func() {
 				return false
 			}, time.Second*2).Should(BeTrue())
 		})
+		It("should skip bootstrap kubeconfig flow if the ~/.byoh/config exists", func() {
```
Comment (mayur-tolexo) [inline agent/host_agent_test.go:566]: You have created `${HOME}/.byoh` directory but didn't clean up

**Review by mayur-tolexo — COMMENTED** [review]
Small nit, overall LGTM

File: agent/host_agent_test.go (hunk 2 above)
Comment (dharmjit) [reply agent/host_agent_test.go:566]: We are creating this inside container and the container gets destroyed after each test.

File: agent/main.go (hunk 1 above)
Comment (dharmjit) [reply agent/main.go:153]: We cannot exit if there are any errors in this. Do you mean to log it or something else? We are checking errors.Is(err, os.ErrNotExist) for the bootstrap kubeconfig flow

Comment (shamsher31) [reply agent/main.go:153]: > We are checking errors.Is(err, os.ErrNotExist) for the bootstrap kubeconfig flow

This is fine

> Do you mean to log it or something else?

Yes, if `os.State` fails we should at least log an error?

Comment (dharmjit) [reply agent/main.go:153]: Logs don't seem very nice
```
E0704 07:00:33.307968  517472 main.go:155]  "msg"="could not lookup kubeconfig file" "error"="stat /home/kokoni/.byoh/config: no such file or directory"  
I0704 07:00:33.308059  517472 main.go:236]  "msg"="initiated bootstrap kubeconfig flow" 
I0704 07:00:33.327298  517472 csr.go:78]  "msg"="CSR request created"  
I0704 07:00:33.327327  517472 csr.go:82]  "msg"="waiting for client certificate to be issued" 
```

**Review by mayur-tolexo — APPROVED** [review]

**Review by shamsher31 — APPROVED** [review]
